// Timesheet Employee MockData
export const employeeData = [
  {
    emp_id: "E12345",
    emp_name: "Arvind",
    role: "Software Engineer",
    projects_ongoing: "2",
    projects_completed: "2",
    planned_hrs: "100",
    unplanned_hrs: "",
    ongoing_projects: [
      {
        project_id: "P001",
        client_name: "Mobile App Development",
        contract_name: "Contract Mobile App Development",
        start_date: "2023-06-01",
        end_date: "2024-12-15",
        planned_hrs: "100",
        unplanned_hrs: "50",
      },
      {
        project_id: "P002",
        client_name: "Data Analytics Platform",
        contract_name: "Contract Data Analytics Platform",
        start_date: "2023-06-01",
        end_date: "2024-11-15",
        planned_hrs: "100",
        unplanned_hrs: "20",
      },
    ],
    completed_projects: [
      {
        project_id: "P003",
        client_name: "Website Redesign",
        contract_name: "Contract Website Redesign",
        start_date: "2023-01-01",
        end_date: "2024-01-15",
        planned_hrs: "100",
        unplanned_hrs: "90",
      },
      {
        project_id: "P004",
        client_name: "API Integration",
        contract_name: "Contract API Integration",
        start_date: "2023-06-01",
        end_date: "2024-02-15",
        planned_hrs: "100",
        unplanned_hrs: "",
      },
    ],
  },
  {
    emp_id: "E12346",
    emp_name: "Kalyan",
    role: "Software Tester",
    projects_ongoing: "2",
    projects_completed: "3",
    planned_hrs: "100",
    unplanned_hrs: "",
    ongoing_projects: [
      {
        project_id: "P005",
        client_name: "Mobile App Development",
        contract_name: "Contract Mobile App Development",
        start_date: "2023-06-01",
        end_date: "2024-12-15",
        planned_hrs: "100",
        unplanned_hrs: "50",
      },
      {
        project_id: "P006",
        client_name: "Data Analytics Platform",
        contract_name: "Contract Data Analytics Platform",
        start_date: "2023-06-01",
        end_date: "2024-11-15",
        planned_hrs: "100",
        unplanned_hrs: "80",
      },
    ],
    completed_projects: [
      {
        project_id: "P007",
        client_name: "One Website Redesign",
        contract_name: "Contract Website Redesign",
        start_date: "2023-01-01",
        end_date: "2024-01-15",
        planned_hrs: "100",
        unplanned_hrs: "50",
      },
      {
        project_id: "P008",
        client_name: "One API Integration",
        contract_name: "Contract API Integration",
        start_date: "2023-06-01",
        end_date: "2024-02-15",
        planned_hrs: "100",
        unplanned_hrs: "",
      },
      {
        project_id: "P009",
        client_name: "Two API Integration",
        contract_name: "Contract API Integration",
        start_date: "2023-06-01",
        end_date: "2024-02-15",
        planned_hrs: "100",
        unplanned_hrs: "",
      },
    ],
  },
];
