name: Build and Deploy to Azure Container App

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Build and push image"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          IMAGE_TAG=${{ steps.vars.outputs.sha_short }}
          docker build . \
            --build-arg REACT_APP_API_ENDPOINT=${{ secrets.REACT_APP_API_ENDPOINT }} \
            --build-arg REACT_APP_SERVER_URL=${{ secrets.REACT_APP_SERVER_URL }} \
            --build-arg APP_ENABLED_PAST_DATES=${{ secrets.APP_ENABLED_PAST_DATES }} \
            --build-arg REACT_APP_CLIENT_ID=${{ secrets.REACT_APP_CLIENT_ID }} \
            --build-arg REACT_APP_AUTHORITY_URL=${{ secrets.REACT_APP_AUTHORITY_URL }} \
            --build-arg REACT_APP_PROFILE=${{ secrets.REACT_APP_PROFILE }} \
            --build-arg REACT_APP_ENABLE_BILLRATE_EDIT=${{ secrets.REACT_APP_ENABLE_BILLRATE_EDIT }} \
            --build-arg REACT_APP_UNLOCKED_ESTIMATION_EDIT=${{ secrets.REACT_APP_UNLOCKED_ESTIMATION_EDIT }} \
            --build-arg REACT_APP_BUSINESS_UNITS=${{ secrets.REACT_APP_BUSINESS_UNITS }} \
            -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/fe-env:v1.0 \
            -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/fe-env:${IMAGE_TAG} .
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/fe-env:v1.0
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/fe-env:${IMAGE_TAG}
