name: SonarQube Scan & Quality Gate Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
  
jobs:
  sonarqube_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.17.0'

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: SonarQube Scan
        run: |
          ./node_modules/sonarqube-scanner/src/bin/sonar-scanner
        env:
          SONAR_USER_HOME: '${{ github.workspace }}/sonar'
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        # Force to fail step after specific time.
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: "Example show SonarQube Quality Gate Status value"
        run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
